name: test_app
description: "A simple test app for women"

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: any

  # state management
  flutter_bloc: any

  # objects equals
  equatable: any

  # data base
  shared_preferences: any

  # sign in
  google_sign_in: any
  flutter_facebook_auth: any

  # firebase
  firebase_core: any
  firebase_auth: any
  firebase_dynamic_links: any
  firebase_database: any

  # dependency injection
  get_it: any

  # ui component
  url_launcher: any
  avatar_glow: ^3.0.1
  carousel_slider: any
  flutter_svg: any
  lottie: any
  numberpicker: any
  animated_text_kit: any
  shimmer: any
  showcaseview: any

  # json
  json_annotation: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/monda/
    - assets/fonts/poppins/
    - assets/fonts/ubuntu/
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: Monda
      fonts:
        - asset: assets/fonts/monda/Monda-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf