name: test_app
description: "A simple test app for women"

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.8

  # state management
  flutter_bloc: ^8.1.6

  # objects equals
  equatable: ^2.0.5

  # data base
  shared_preferences: ^2.2.3

  # sign in
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1

  # firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  firebase_dynamic_links: ^6.0.2
  firebase_database: ^11.0.2

  # dependency injection
  get_it: ^7.7.0

  # ui component
  avatar_glow: ^3.0.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  numberpicker: ^2.1.2
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  showcaseview: ^3.0.0
  audioplayers: ^6.0.0
  vibration: ^1.9.0

  # web
  url_launcher: ^6.3.0

  # json
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/monda/
    - assets/fonts/poppins/
    - assets/fonts/ubuntu/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: Monda
      fonts:
        - asset: assets/fonts/monda/Monda-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf